src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Money\Currency;
use Money\Money;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    const CURRENCY_CODE='UAH';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Secret::class, mappedBy="product_id")
     */
    private $secrets;

    /**
     * @ORM\Column(type="text")
     */
    private $photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="product")
     */
    private $orders;

    public function __construct()
    {
        $this->name = '';
        $this->description = '';
        $this->price = 0;
        $this->secrets = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Secret[]
     */
    public function getSecrets(): Collection
    {
        return $this->secrets;
    }

    public function addSecret(Secret $secret): self
    {
        if (!$this->secrets->contains($secret)) {
            $this->secrets[] = $secret;
            $secret->setProduct($this);
        }

        return $this;
    }

    public function removeSecret(Secret $secret): self
    {
        if ($this->secrets->removeElement($secret)) {
            // set the owning side to null (unless already changed)
            if ($secret->getProduct() === $this) {
                $secret->setProduct(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPriceAmount(): int
    {
        return $this->price;

    }

    public function getPrice(): Money
    {
        return new Money($this->price, new Currency(self::CURRENCY_CODE));
    }

    public function setPrice(Money $price): self
    {
        $this->price = $price->getAmount();

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setProduct($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getProduct() === $this) {
                $order->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/StoreController.php
<?php

namespace App\Controller;

use App\Entity\City;
use App\Entity\Order;
use App\Entity\Product;
use App\Repository\CityRepository;
use App\Repository\ProductRepository;
use App\Repository\SecretRepository;
use App\Service\OrderService;
use App\Service\ProductService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StoreController extends AbstractController
{
    private ProductRepository $productRepository;
    private CityRepository $cityRepository;
    private ProductService $productService;
    private SecretRepository $secretRepository;
    private OrderService $orderService;

    public function __construct(
        ProductRepository $productRepository,
        CityRepository $cityRepository,
        SecretRepository  $secretRepository,
        ProductService $productService,
        OrderService $orderService
    ) {
        $this->cityRepository = $cityRepository;
        $this->productRepository = $productRepository;
        $this->secretRepository = $secretRepository;
        $this->productService = $productService;
        $this->orderService = $orderService;
    }

    /**
     * @Route("/", name="cities")
     */
    public function index(Request $request): Response
    {
        $cityCollection = $this->cityRepository->findAll();
        $secretRepository = $this->secretRepository;

        array_filter($cityCollection, function ($city) use ($secretRepository) {
            if ($secretRepository->findAllSecretsByCity($city) > 1) {
                return true;
            }

            return false;
        });

        if (empty($cityCollection)) {
            return $this->render('store/empty.html.twig', []);
        }

        return $this->render('store/cities.html.twig', [
            'cities' => $cityCollection,
        ]);
    }

    /**
     * @Route("/store/{id}", name="store")
     * @ParamConverter("id", class="App\Entity\City")
     */
    public function store(City $city): Response
    {
        $secretCollection = $city->getSecrets();
        $productCollection = $this->productService->findAllByAvailableSecrets($secretCollection);

        return $this->render('store/index.html.twig', [
            'city' => $city,
            'products' => $productCollection,
        ]);
    }

    /**
     * @Route("/store/{id}/product/{item}", name="view_product", methods={"GET", "POST"})
     * @ParamConverter("id", class="App\Entity\City")
     * @ParamConverter("item", class="App\Entity\Product")
     */
    public function view(Request $request, City $city, Product $product)
    {
        $secrets = $this->secretRepository->findAllSecretsByCityAndProduct($city, $product);
        $preparedSecrets = $this->productService->groupSecretsByDistrict($secrets);
        $orderEntity = new Order();

        $customerOrderForm = $this->createFormBuilder($orderEntity)
            ->add('productSecret', ChoiceType::class, [
                'choices' => $preparedSecrets,
                'choice_label' => function ($choice, $key, $value) {
                    return $choice->getProduct()->getName() . '/' . $choice->getPackage()->getSize() . 'g.';
                }
            ])
            ->add('buy', SubmitType::class, ['label' => 'Buy'])
            ->getForm();

        $customerOrderForm->handleRequest($request);

        if ($customerOrderForm->isSubmitted()) {
            $orderEntity = $this->orderService->createOrder($orderEntity, $this->getUser());

            return new RedirectResponse($this->generateUrl('order_payment_method', ['id' => $orderEntity->getId()]));
        }

        return $this->render('store/product.html.twig', [
            'product' => $product,
            'order_form' => $customerOrderForm->createView(),
        ]);
    }
}

templates/store/cities.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StoreController!{% endblock %}

{% block body %}

{% for city in cities %}
  <div class="card-body">
    <a href="{{ url('store', {"id":city.id}) }}">{{ city.name }}</a>
  </div>
{% endfor %}
{% endblock %}

templates/store/empty.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StoreController!{% endblock %}

{% block body %}

    <h2>Sorry, but now store is empty</h2>
{% endblock %}

templates/store/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StoreController!{% endblock %}

{% block body %}
  {% if (products|length < 1) %}
    <div class="col-12">
        <h2>Sorry, now any product isn't available. Please check later</h2>
    </div>
  {% else %}
    {% for product in products %}
      <a href="{{ url('view_product', {id:city.id,item:product.id}) }}">{{ product.name }}</a>
    {% endfor %}

  {% endif %}
{% endblock %}

templates/store/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StoreController!{% endblock %}

{% block body %}
  <div class="col-4">
    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
  </div>
  <div class="col-8">
    <div class="row">
      <div class="text-center">
        <!-- Product name-->
        <h5 class="fw-bolder">{{ product.name }}</h5>
        <!-- Product reviews-->
        <div class="d-flex justify-content-center small text-warning mb-2">
          <div class="bi-star-fill"></div>
          <div class="bi-star-fill"></div>
          <div class="bi-star-fill"></div>
          <div class="bi-star-fill"></div>
          <div class="bi-star-fill"></div>
        </div>
        <!-- Product price-->
        <span class="text-muted text-decoration-line-through">{{ product.priceAmount|format_currency('UAH') }}</span>
        <div class="text-body">
          {{ product.description }}
        </div>
      </div>
    </div>
    <div class="row">
      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
        {{ form(order_form) }}
      </div>
    </div>
  </div>

<!-- Product details-->

{% endblock %}